### ISSUE TITLE
Demande d'adhésion au club d'informatique

### ISSUE THREAD

**Issue by papsonic** [cih-hoche/Challs#1]
Bonjour,

Je suis en classe de 3ème et je souhaite rejoin Hoche pour l'année prochaine (scolaire) 😅.
J'aime beaucoup la programmation et je suis un fan de python (et scratch ^^) ! 

Désolé pour ouvrir une issue ici mais je ne savais pas comment vous contacter autrement !! 😁

En tout cas merci pour le club..

J'espère pouvoir être admis pour l'année prochaine et de pouvoir intégerer ce club d'informatique en tout cas.
Le test d'entrée n'est pas trop difficile ???!!!

En tout cas merci pour le club...

Bonne journée

**Comment by DocSystem** [comment]
Hey !
Pas de problème !
Si tu souhaite nous rejoindre l'année prochaine tu es le bienvenu, par contre GitHub n'est pas vraiment le bon endroit pour en parler.

Je te joins ci-dessous notre adresse mail ainsi que les liens de notre serveur Discord et notre compte Instagram (sur lequel tu peux aussi nous contacter) :
- [cihoche@gmail.com](mailto:cihoche@gmail.com)
- [Notre Discord](https://discord.gg/BEAA3AyRae)
- [Notre Instagram](https://instagram.com/cihoche)
